# Generated by Django 4.2.17 on 2025-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='avatar'),
        ),
    ]
